// proyecto_react_vite/src/components/ArticlePreview/ArticlePreview.tsx
import React, { useState, MouseEvent } from "react";
import ApiImage from "@/api/ApiImage";
import Dayjs from "@/components/Dayjs";
import { ArticleResponse } from '@/models/ArticleResponse.model';
import { useNavigateWithTransitions } from "@/hooks/useNavigateWithTransitions";
import { useDispatch } from "react-redux";
import { setCurrentArticle } from "@/store/article/articles.actions";
import styles from './ArticlePreview.module.css';

export interface ArticlePreviewProps {
  article: ArticleResponse;

  follow(article: ArticleResponse): void;
};

const ArticlePreview: React.FC<ArticlePreviewProps> = ({article, follow}) => {
  const navigate = useNavigateWithTransitions();
  const dispatch = useDispatch();

  const [btnSeguir, setBtnSeguir] = useState({disabled: false});

  const callFollow = (event: MouseEvent<HTMLButtonElement>): void => {
    setBtnSeguir({disabled: true});
    follow(article);
  }

  const gotToArticlePage = () => {
    dispatch(setCurrentArticle(article));
    navigate('/blog/article/' + article._id);
  }

  return (
    <article
      id={article._id} className={styles.article_preview_container}
      style={{viewTransitionName: `article-card-${article._id}`}}
    >
      <figure className={styles.article_preview_container__image_container}
              onClick={gotToArticlePage}
      >
        <img src={ApiImage.getImageUrl(article.image)} alt="Article Image" />
      </figure>
      <div className={styles.article_preview_container__card_info}>
        <Dayjs
        >
          {article.date}
        </Dayjs>
        <h2>
          {article.title}
        </h2>
        <p>{article.content}</p>
        <div className={styles.article_preview_container__card_info__buttonbar}>
          <button className={styles.article_preview_container__card_info__star_button} onClick={callFollow} disabled={btnSeguir.disabled}>
            <span className={styles.star_icon}></span>
          </button>
          <a onClick={gotToArticlePage} className={styles.article_preview_container__card_info__read_more}>
            <span >Leer más ...</span>
          </a>
        </div>

      </div>

    </article>
  );
}

export default ArticlePreview;

// proyecto_angular/src/app/components/article-preview/article-preview.component.ts
import { Component, Input } from '@angular/core';
import { Article } from "@/models/Article.model";
import { Router, RouterLink } from "@angular/router";
import { getImageUrl} from "@/libs/ImageUtils";
import { DayjsComponent } from "@/components/dayjs/dayjs.component";
import { AppState } from "@/store/app.state";
import { Store } from "@ngrx/store";
import { ModuleArticleActions } from "@/store/storemodule-article/module-article.actions";

@Component({
  selector: 'app-article-preview',
  standalone: true,
  imports: [
    RouterLink,
    DayjsComponent
  ],
  templateUrl: './article-preview.component.html',
  styleUrl: './article-preview.component.css'
})
export class ArticlePreviewComponent {
  protected readonly getImageUrl = getImageUrl;

  @Input()
  article: Article = {
    _id: "0",
    title: "",
    content: "",
    date: "",
    image: "",
    __v: 0
  }

  constructor(
    private router: Router,
    private store: Store<AppState>
  ) {
  }

  protected goToArticle(): void {
    this.store.dispatch(ModuleArticleActions.setArticle({article: this.article}));
    this.router
      .navigate(['/blog/article', this.article._id])
      .then();
  }


}

<article [id]="article._id" class="article-card"
         [style.view-transition-name]="'article-card-' + article._id"
>
  <figure class="article-card__imageContainer">
    <a [routerLink]="'/blog/article/' + article._id">
      <img [src]="getImageUrl(article.image)" [alt]="article.title"/>
    </a>
  </figure>
  <div class="article-card__info">
    <app-dayjs class="article-card__date" [dateString]="article.date"></app-dayjs>
    <h2>{{ article.title }}</h2>
    <a [routerLink]="'/blog/article/' + article._id" class="btn">
      Leer más ...
    </a>
  </div>

</article>
