// proyecto_vue_vite/src/components/Article.vue
<template>
  <article :id="props.article._id" class="article-item article-detail">
    <div class="image-wrap">
      <img :src="ApiImage.getImageUrl(props.article.image)" alt="Article Image" />
    </div>
    <div class="article-button-bar">
      <button @click="editArticle(props.article._id)" class="btn btn-warning">Editar</button>
      <button @click="deleteArticle(props.article._id)" class="btn btn-danger">Eliminar</button>
    </div>
    <h1 class="subheader">{{ props.article.title }}</h1>
    <Dayjs class="date" :dateString="props.article.date"></Dayjs>
    <div class="article-text">
      {{ props.article.content }}
    </div>
  </article>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import ApiArticle, { ArticleResponse } from '../api/ApiArticle';
import ApiImage from '../api/ApiImage';
import UseFetchData from '../classes/UseFetchData';
import { useRoute } from "vue-router";
import Dayjs from './Dayjs.vue';

const route = useRoute();
const articleId = route.params.articleId as string;


type ArticleProps = {
  article: ArticleResponse
}

const props = defineProps<ArticleProps>()

const editArticle = (articleId: string) => {
  console.log(articleId);
}

const deleteArticle = (articleId: string) => {
  console.log(articleId);
}


const article = ref<UseFetchData<ArticleResponse>>(new UseFetchData<ArticleResponse>());
const loading = ref<boolean>(true);
const { promise, abortController } = ApiArticle.getArticleById(articleId);


onMounted(() => {
  promise.then((wsResult) => {
    article.value.setFetchData(wsResult);
    loading.value = false;
  });
});

onUnmounted(() => {
  abortController.abort();
})



</script>

// proyecto_react_vite/src/Pages/Article.tsx
import ApiConstant from "../api/ApiConstant";
import Sidebar from "../components/Sidebar";
import { useParams } from "react-router-dom";
import useFetch from "../custom_hooks/useFetch";
import NotFound from "./NotFound";
import Loading from "../components/Loading";
import Dayjs from "../components/Dayjs";
import ApiImage from "../api/ApiImage";
import Error from "../components/Error";
import {ArticleResponse} from "../api/ApiArticle";

type ArticleUrlParams = {
  id: string;
}

function renderArticle(article: ArticleResponse): JSX.Element {
  return (
    <article id={article._id} className="article-item article-detail">
      <div className="image-wrap">
        <img src={ApiImage.getImageUrl(article.image)} alt="Article Image" />
      </div>
      <h1 className="subheader">{article.title}</h1>
      <Dayjs className="date">{article.date}</Dayjs>
      <div className="article-text">
        {article.content}
      </div>
    </article>
  );
}


const Article = (): JSX.Element => {
  const { id } = useParams<ArticleUrlParams>();
  if (id === undefined) return <NotFound></NotFound>

  const { data, loading, error } = useFetch<ArticleResponse>(`${ApiConstant.ARTICLE.GET_BY_ID}/${id}`);

  return (
    <div className="center">
      <section id="content">
        <div id="article-container">
          {loading && <Loading></Loading>}
          {error && <Error></Error>}
          {data.response && renderArticle(data.response)}
        </div>
      </section>
      <Sidebar isBlog></Sidebar>
    </div>
  );
}

export default Article;
