// proyecto_angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { SliderComponent } from "@/components/slider/slider.component";
import { AsideComponent } from "@/components/sidebar/aside/aside.component";
import { PageContentComponent } from "@/components/page-content/page-content.component";

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    SliderComponent,
    AsideComponent,
    PageContentComponent
  ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {

}

<app-page-content
  [isHomePage]="true"
  sliderTitle="Welcome to the Blog with Angular"
>
  <h2 class="subheader">Last Articles</h2>
</app-page-content>

// proyecto_react_vite/src/pages/Home.tsx
import ArticleListLast from '@/components/ArticleListLast';
import Sidebar from '@/components/Sidebar';
import Slider from '@/components/Slider';

const Home = () => {
  return (
    <>
      <Slider isHome title="Welcome This Blog written in ReactJs"></Slider>
      <section id="content" className="page-home">
        <h2 className="subheader">Last published Articles</h2>
        {/* <!-- LISTADO ULTIMOS ARTICULOS ARTICULOS --> */}
        <ArticleListLast></ArticleListLast>
      </section>
      <Sidebar></Sidebar>
    </>
  );
}


export default Home;
