// proyecto_angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from "@angular/router";

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    RouterLink
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}

<header class="header">
  <!-- LOGO -->
  <div routerLink="/" class="header__logo">
    <img src="assets/images/logo.svg" alt="Angular Logo">
    <span class="header__brand">
      <strong>Angular</strong>
    </span>
  </div>

</header>

// proyecto_vue_vite/src/components/HeaderComponent.vue
<template>
    <header id="header" class="header">
      <!-- LOGO -->
      <div id="logo">
        <img src="../assets/images/vue.svg" alt="Logotipo" class="app-logo">
        <span id="brand">
            <strong>Vue</strong>JS
        </span>
        </div>

  </header>
</template>

<script setup lang="ts">
</script>
