// proyecto_angular/src/app/components/slider/slider.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from "@angular/router";

@Component({
  selector: 'app-slider',
  standalone: true,
  imports: [
    RouterLink
  ],
  templateUrl: './slider.component.html',
  styleUrl: './slider.component.css'
})
export class SliderComponent {

  @Input()
  public title: string = '';

  @Input()
  public isHome: boolean = false;

}

<div
  class="slider"
  [class]="{
    'slider--big': showBigSlider,
    'slider--small': !showBigSlider
  }"
  [style.view-transition-name]="'slider'"
>
  <h1>{{ title }}</h1>
  @if(showBigSlider) {
    <a routerLink="/blog" class="btn-white">Go to Blog</a>
  }
</div>

// proyecto_vue_vite/src/components/Slider.vue
<template>
  <div id="slider" :class="isHome ? 'slider-big' : 'slider-small'">
    <h1>{{ title }}</h1>
    <router-link v-if="isHome" to="/blog" class="btn-white">Ir al blog</router-link>
  </div>
</template>

<script setup lang="ts">

type SliderProps = {
  title: string,
  isHome?: boolean
};

defineProps<SliderProps>();

</script>
