// proyecto_react_vite/src/components/Slider.tsx
import { NavLink } from "react-router-dom";

export type SliderProps = {
  title: string,
  isHome?: boolean
};

function Slider(props: SliderProps): JSX.Element {
  const className = props.isHome ? "slider-big" : "slider-small";

  return (
    <div id="slider" className={className}>
      <h1>{props.title}</h1>
      {props.isHome && <NavLink to="/blog" className="btn-white">Ir al blog</NavLink>}
    
    </div>
  );
}

export default Slider;

// proyecto_vue_vite/src/components/Slider.vue
<template>
  <div id="slider" :class="isHome ? 'slider-big' : 'slider-small'">
    <h1>{{ title }}</h1>
    <router-link v-if="isHome" to="/blog" class="btn-white">Ir al blog</router-link>
  </div>
</template>

<script setup lang="ts">

type SliderProps = {
  title: string,
  isHome?: boolean
};

defineProps<SliderProps>();

</script>
