// proyecto_vue_vite/src/components/ArticleList.vue
<template>
  <Loading v-if="loading"></Loading>
  <div v-else>
    <SelectedArticle v-if="selectedArticle" :title=selectedArticle></SelectedArticle>
    <Error v-if="articleList?.hasErrors()" :errors="props.articleList?.errorMessages"></Error>
    <div v-else  class="article-container">
      <ArticlePreview v-if="props.articleList?.hasResponse()" v-for="article in articleList?.response" :key="article._id"
        :article="article" @setFavorite="setSelectedArticle"></ArticlePreview>
      <NoResults v-else></NoResults>
    </div>

  </div>
</template>

<script setup lang="ts">
import { ArticleResponse } from '../api/ApiArticle';
import UseFetchData from '../classes/UseFetchData';
import ArticlePreview from './ArticlePreview.vue';
import SelectedArticle from './SelectedArticle.vue';
import Loading from '../components/Loading.vue'
import NoResults from '../components/NoResults.vue'
import Error from '../components/Error.vue'
import { ref } from 'vue';


type ArticleListProps = {
  loading: boolean,
  articleList: UseFetchData<ArticleResponse[]>
}

const props = defineProps<ArticleListProps>();
const selectedArticle = ref<string>('');


const setSelectedArticle = (article: ArticleResponse) => {
  selectedArticle.value = article.title;
}

</script>

// proyecto_react_vite/src/components/ArticleList.tsx
import { useState } from "react";
import ApiConstant from "../api/ApiConstant";
import useFetch from "../custom_hooks/useFetch";
import UseFetchData from "../classes/UseFetchData";
import { ArticleResponse } from "../api/ApiArticle";
import Error from "./Error";
import Loading from "./Loading";
import ArticlePreview from "./ArticlePreview";



type ArticleListProps = {
  articlesApiUrl?: string
}

type ArticleListState = {
  followArticleTitle: string
}


function showArticleList(fetchData: UseFetchData<ArticleResponse[]>, followArticle: (f: ArticleResponse) => void): JSX.Element {
  if(fetchData.hasResponse()){
    const articleList = fetchData.response!;
    return (
      <div id="article-container">
        {articleList.map(article => (<ArticlePreview key={article._id} {...article} follow={followArticle} />))}
      </div>
    );
  } else {
    return (
      <p>Todavia no existen articulos para mostar</p>
    );
  }
}


const ArticleList = (props: ArticleListProps): JSX.Element => {

  const apiUrl = props.articlesApiUrl ? props.articlesApiUrl : ApiConstant.ARTICLE.GET_ALL_ARTICLES;

  const { data, error, loading } = useFetch<ArticleResponse[]>(apiUrl);
  const [blogState, setBlogState] = useState<ArticleListState>({
    followArticleTitle: ''
  });

  const followArticle = (article: ArticleResponse): void => {
    setBlogState({ followArticleTitle: article.title });
  };

  return (
    <section id="content">
      {/* Aqui se cargaran mediante api rest, la lista de articulos */}
      {blogState.followArticleTitle && <div className="message">{blogState.followArticleTitle}</div>}
      {loading && <Loading></Loading>}
      {error && <Error></Error>}
      {data.hasErrors() && <Error errors={data.errorMessages}></Error>}
      {data.isSuccessful && showArticleList(data, followArticle)}
    </section>
  );
}

export default ArticleList
