// proyecto_vue_vite/src/components/ArticlePreview.vue
<template>
  <article :id="article._id" class="article-item">
    <div class="image-wrap">
      <router-link :to="'/blog/article/' + article._id">
        <img :src="ApiImage.getImageUrl(article.image)" :alt="article.title" />
      </router-link>
    </div>
    <button class="btn-follow star-button" @click="buttonFollowPressed" :disabled="buttonFollorPressed">
      <span class="star-icon"></span>
    </button>
    <h2>{{ article.title }}</h2>
    <Dayjs class="date" :dateString="article.date"></Dayjs>
    <router-link :to="'/blog/article/' + article._id" class="btn">
      Leer más ...
    </router-link>
  </article>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import ApiImage from "../api/ApiImage";
import { ArticleResponse } from "../api/ApiArticle";
import Dayjs from "./Dayjs.vue";


const emit = defineEmits<{
  setFavorite: [article: ArticleResponse]
}>();

type ArticlePreviewProps = {
  article: ArticleResponse
}

const buttonFollorPressed = ref<boolean>(false);
const props = defineProps<ArticlePreviewProps>()


const buttonFollowPressed = () => {
  buttonFollorPressed.value = true;
  emit('setFavorite', props.article);
}

</script>

// proyecto_react_vite/src/components/ArticlePreview.tsx
import React, { Component, MouseEvent } from "react";
import { Link } from 'react-router-dom';
import ApiImage from "../api/ApiImage";
import Dayjs from "./Dayjs";
import { ArticleResponse } from '../api/ApiArticle';

export interface ArticlePreviewProps extends ArticleResponse {
  follow(article: ArticlePreviewProps): void;
};


type ArticlePreviewState = {
  btnSeguir: {
    disabled: boolean
  }
};


class ArticlePreview extends Component<ArticlePreviewProps, ArticlePreviewState> {

  state = {
    btnSeguir: { disabled: false }
  }

  private callFollow = (event: MouseEvent<HTMLButtonElement>): void => {
    this.setState({ ...this.state, btnSeguir: { ...this.state.btnSeguir, disabled: true } });
    this.props.follow(this.props);
  }


  render() {
    const { _id, title, image, date, follow } = this.props;

    return (
      <article id={_id} className="article-item">
        <div className="image-wrap">
          <Link to={'/blog/article/' + _id}>
            <img src={ApiImage.getImageUrl(image)} alt="Article Image" />
          </Link>
        </div>
        <button className="btn-follow star-button" onClick={this.callFollow} disabled={this.state.btnSeguir.disabled}>
          <span className="star-icon"></span>
        </button>
        <h2>{title}</h2>
        <Dayjs className="date">{date}</Dayjs>
        <Link to={'/blog/article/' + _id} className="btn">
          Leer más ...
        </Link>
      </article>
    );
  }
}

export default ArticlePreview;
