// proyecto_vue_vite/src/components/Menu.vue
<template>
  <nav id="menu">
    <ul>
      <li>
        <a class="navlink_active" href="/">Inicio</a>
      </li>
      <li>
        <a class="navlink_active" href="blog">Blog</a>
      </li>
      <li>
        <a class="navlink_active" href="formulario">Formulario</a>
      </li>
    <li>
      <a class="navlink_active" href="pagina1/funcional/receta">Pagina 1</a>
    </li>
    <li>
      <a class="navlink_active" href="pagina2">Pagina 2</a>
    </li>
  </ul>
</nav></template>

// proyecto_react_vite/src/components/Menu.tsx
import LinkWithTransition from "@/components/LinkWithTransition";

const Menu = (): JSX.Element => {
  return (
    < nav id="menu">
      <ul>
        <li><LinkWithTransition href="/">Inicio</LinkWithTransition></li>
        <li><LinkWithTransition href="/blog">Blog</LinkWithTransition></li>
        <li><LinkWithTransition href="/formulario">Formulario</LinkWithTransition></li>
        <li><LinkWithTransition href="/pagina1/funcional/receta">Pagina 1</LinkWithTransition></li>
        <li><LinkWithTransition href="/pagina2">Pagina 2</LinkWithTransition></li>
      </ul>
    </nav>
  );
}

export default Menu;
