// proyecto_vue_vite/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <SidebarArticleNew v-if="isBlog" />
    <SidebarSearchArticleForm></SidebarSearchArticleForm>
  </aside>
</template>

<script setup lang="ts">
import SidebarArticleNew from './SidebarArticleNew.vue';
import SidebarSearchArticleForm from './SidebarSearchArticleForm.vue';

type SidebarProps = {
  isBlog?: boolean
};

defineProps<SidebarProps>()
</script>

// proyecto_react_vite/src/components/Sidebar.tsx
import SidebarSearchArticleForm from "./SidebarSearchArticleForm";
import SidebarArticleNew from "./SidebarArticleNew";


export type SidebarProps = {
  isBlog?: boolean
};


const Sidebar = (props: SidebarProps): JSX.Element => {
  return (
    <aside id="sidebar">
      {props.isBlog && <SidebarArticleNew />}
      <SidebarSearchArticleForm></SidebarSearchArticleForm>
    </aside>
  );
}

export default Sidebar;
