// proyecto_vue_vite/src/components/Menu.vue
<template>
  <nav id="menu">
    <ul>
      <li>
        <a class="navlink_active" href="/">Inicio</a>
      </li>
      <li>
        <a class="navlink_active" href="blog">Blog</a>
      </li>
      <li>
        <a class="navlink_active" href="formulario">Formulario</a>
      </li>
    <li>
      <a class="navlink_active" href="pagina1/funcional/receta">Pagina 1</a>
    </li>
    <li>
      <a class="navlink_active" href="pagina2">Pagina 2</a>
    </li>
  </ul>
</nav></template>

// aprendiendo_react/src/components/Menu.tsx
import React, { Component } from "react";

class Menu extends Component {

  public render(): JSX.Element {
    return (
      < nav id="menu" >
        <ul>
          <li><a href="index.html">Inicio</a></li>
          <li><a href="blog.html">Blog</a></li>
          <li><a href="formulario.html">Formulario</a></li>
          <li><a href="#">Pagina 1</a></li>
          <li><a href="#">Pagina 2</a></li>
        </ul>
      </nav >
    );
  }
}

export default Menu;
